import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import design from "../public/design.png";
import code from "../public/code.png";
import logo from "../public/logo.png";
import logonew from "../public/logonew.png";
import {
  AiOutlineInstagram,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { SiWebflow } from "react-icons/si";
import { FiFigma } from "react-icons/fi";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

import { useState } from "react";

import sandeep from "../public/sandeep.png";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sandeep KS Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico?v=2" />
      </Head>
      <main className=" bg-[#f5f7fa] px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 flex justify-between dark:text-white">
            <div className="w-40 cursor-pointer mt-0 mb-0">
              <Image
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={logo}
              />
            </div>

            <ul className="mb-4 flex items-center gap-3">
              <li>
                <a
                  href="mailto:ss2359215@gmail.com"
                  class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
                >
                  <span class="absolute px-4 py-2 top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                  <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                  <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                  <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                  <span class="relative">Get in touch</span>
                </a>
              </li>
              <li>
                <a
                  href="https://drive.google.com/file/d/1-LJpk3OtS8kXhLPbFMLlcsRmnsRYgV3g/view?usp=sharing"
                  class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
                >
                  <span class="absolute px-4 py-2 top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                  <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                  <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                  <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                  <span class="relative">Resume</span>
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center">
            <h2 className="text-5xl text-teal-600 font-semibold dark:text-teal-400 md:text-6xl">
              Hi, I'm Sandeep. Nice to meet you.
            </h2>
            <h3 className="text-3xl py-2 dark:text-white md:text-4xl">
              Designer & Frontend Developer
            </h3>

            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/sandysks">
                <AiFillGithub />
              </a>
              <a href="https://www.linkedin.com/in/sandeep-kumar-singh-7ba716194/">
                <AiFillLinkedin />
              </a>
              <a href="https://www.instagram.com/sandy.here_/">
                <AiOutlineInstagram />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-10 md:h-96 md:w-96">
              <Image src={sandeep} />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-2xl py-1 text-center mt-10 dark:text-white ">
              I design and build beautiful websites for businesses around the
              globe. If you need a modern and powerful website, send me an
              email. If we are a good fit, I will give you a time and cost
              estimate.
            </h3>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-2xl font-medium tracking-[.4rem] pt-8 pb-2 text-teal-600  ">
                DESIGNER
              </h3>
              <p className="py-2 text-justify font-medium text-lg">
                I design beautiful and powerful websites for modern businesses.
                Any business today needs a website that wins customers’ trust
                and helps you do your business well. I make sure your website is
                up to that standard.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Webflow</p>
              <p className="text-gray-800 py-1">Pen & Paper</p>
              <p className="text-gray-800 py-1">Blender</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h3 className="text-2xl tracking-[.4rem] font-medium text-teal-600 pt-8 pb-2 ">
                FRONTEND DEVELOPER
              </h3>
              <p className="py-2 font-medium text-justify text-lg">
                I build websites in Webflow where I can create responsive,
                powerful, and fully custom websites and later code them with
                React JS. Plus, Webflow has an incredibly simple Content Editor
                for you and your team to edit website content quickly and
                easily.
              </p>
              <h4 className="py-4 text-teal-600">Dev Tools I Use</h4>
              <p className="text-gray-800 py-1">VS Code</p>
              <p className="text-gray-800 py-1">Atom</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
              <p className="text-gray-800 py-1">Tailwind</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div className="text-center">
            <h3 className="text-5xl py-1  text-teal-400 font-semibold ">
              My Recent Work With React JS
            </h3>
            <p className="text-xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              Here are a few past React JS projects I've worked on.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <a
                href="https://sandysks.github.io/gpt/"
                class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
              >
                <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                <span class="relative">
                  <Image
                    className="rounded-lg object-cover"
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    src={web1}
                  />
                </span>
              </a>
              <div className="lg:flex justify-between">
                <a
                  href="#_"
                  class="px-5 py-2.5 relative rounded cursor-auto group text-white font-medium inline-block"
                >
                  <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                  <span class="relative">
                    HTML | CSS | JavaScript | React JS
                  </span>
                </a>
                <div className="lg:flex justify-between gap-2">
                  <a
                    href="#_"
                    class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                    <span class="relative">Live ⇑</span>
                  </a>
                  <a
                    href="#_"
                    class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                    <span class="relative">Code ⇒</span>
                  </a>
                  <a
                    href="https://github.com/sandysks/gpt"
                    class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                    <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                    <span class="relative">
                      <AiFillGithub className="w-5 h-5" />
                    </span>
                  </a>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div>
                <h1 className="text-5xl mt-16 text-center text-teal-400">
                  Modern UI/UX GPT-3
                </h1>
                <p className="text-lg leading-9 text-white text-center mt-5">
                  Build for a concept project - GPT3. I took the premade Figma
                  design and turned it into a fully responsive react web
                  application covering almost all devices.
                </p>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div>
                <h1 className="text-5xl mt-16 text-center text-teal-400">
                  Restaurant Landing Page
                </h1>
                <p className="text-lg leading-9 text-white text-center mt-5">
                  This is a homepage design and build for a concept project -
                  Gericht Restaurant. I took the premade Figma design and turned
                  it into a fully responsive React application. It includes a
                  promo video and a beautifully designed photo gallery.
                </p>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://sandysks.github.io/gericht-restaurant/"
                class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
              >
                <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                <span class="relative">
                  <Image
                    className="rounded-lg object-cover"
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    src={web2}
                  />
                </span>
              </a>
              <div className="lg:flex justify-between">
                <a
                  href=""
                  class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                >
                  <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                  <span class="relative">
                    HTML | CSS | JavaScript | React JS
                  </span>
                </a>
                <div className="lg:flex justify-between gap-2">
                  <a
                    href="#_"
                    class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                    <span class="relative">Live ⇑</span>
                  </a>
                  <a
                    href="#_"
                    class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                    <span class="relative">Code ⇒</span>
                  </a>
                  <a
                    href="https://github.com/sandysks/gericht-restaurant"
                    class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                    <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                    <span class="relative">
                      <AiFillGithub className="w-5 h-5" />
                    </span>
                  </a>
                </div>
              </div>
            </div>

            <div className="basis-1/3 flex-1">
              <a
                href="https://sandysks.github.io/tindog/"
                class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
              >
                <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                <span class="relative">
                  <Image
                    className="rounded-lg object-cover"
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    src={web3}
                  />
                </span>
              </a>

              <div className="lg:flex justify-between">
                <a
                  href="#_"
                  class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                >
                  <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                  <span class="relative">
                    HTML | CSS | JavaScript | BootStrap
                  </span>
                </a>
                <div className="lg:flex justify-between gap-2">
                  <a
                    href="#_"
                    class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                    <span class="relative">Live ⇑</span>
                  </a>
                  <a
                    href="#_"
                    class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                    <span class="relative">Code ⇒</span>
                  </a>
                  <a
                    href="https://github.com/sandysks/tindog"
                    class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                    <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                    <span class="relative">
                      <AiFillGithub className="w-5 h-5" />
                    </span>
                  </a>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div>
                <h1 className="text-5xl mt-16 text-center text-teal-400">
                  Tindog
                </h1>
                <p className="text-lg leading-9 text-white text-center mt-5">
                  This is a homepage design and build for a concept project –
                  Tindog,a dating website for pets. I designed the page first
                  then built a responsive web page using BootStrap.
                </p>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div>
                <h1 className="text-5xl mt-16 text-center text-teal-400">
                  Drum Kit
                </h1>
                <p className="text-lg leading-9 text-white text-center mt-5">
                  This is a single-page website built for a concept project -
                  Drum Kit. You can play different musical instruments either
                  with the keyboard keys or by using the mouse.
                </p>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://sandysks.github.io/DrumKit/"
                class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
              >
                <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                <span class="relative">
                  <Image
                    className="rounded-lg object-cover"
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    src={web4}
                  />
                </span>
              </a>
              <div className="lg:flex justify-between">
                <a
                  href=""
                  class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                >
                  <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                  <span class="relative">HTML | CSS | JavaScript</span>
                </a>
                <div className="lg:flex justify-between gap-2">
                  <a
                    href="#_"
                    class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                    <span class="relative">Live ⇑</span>
                  </a>
                  <a
                    href="#_"
                    class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                    <span class="relative">Code ⇒</span>
                  </a>
                  <a
                    href="https://github.com/sandysks/DrumKit"
                    class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                    <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                    <span class="relative">
                      <AiFillGithub className="w-5 h-5" />
                    </span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div className="text-center">
            <h3 className="text-5xl py-1  text-teal-400 font-semibold ">
              My Recent Work With Figma and Webflow
            </h3>
            <p className="text-xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              Here are a few past Web Design projects I've worked on.
            </p>
          </div>
          <div className="flex flex-col gap-10 pt-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <a
                href="https://sandeeps-top-notch-site-fc4aa0.webflow.io/"
                class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
              >
                <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                <span class="relative">
                  <Image
                    className="rounded-lg object-cover"
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    src={web5}
                  />
                </span>
              </a>
              <div className="lg:flex justify-between">
                <a
                  href="#_"
                  class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                >
                  <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                  <span class="relative">Figma | Webflow</span>
                </a>
                <div className="lg:flex justify-between gap-2">
                  <a
                    href="#_"
                    class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                    <span class="relative">Live ⇑</span>
                  </a>
                  <a
                    href="#_"
                    class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                    <span class="relative">Read-Only Links ⇒</span>
                  </a>
                  <a
                    href="https://www.figma.com/file/xkzrg2G4T9DctqYnZd456i/Team-App?node-id=693%3A0&t=d89Je62pRQGrg3uz-1"
                    class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                    <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                    <span class="relative">
                      <FiFigma className="w-5 h-5" />
                    </span>
                  </a>
                  <a
                    href="https://preview.webflow.com/preview/sandeeps-top-notch-site-fc4aa0?utm_medium=preview_link&utm_source=designer&utm_content=sandeeps-top-notch-site-fc4aa0&preview=2eaa321efe0629f433d2f3e18f48d6fd&workflow=preview"
                    class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                    <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                    <span class="relative">
                      <SiWebflow className="w-5 h-5" />
                    </span>
                  </a>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="">
                <h1 className="text-5xl mt-10 text-center text-teal-400">
                  Team App Website
                </h1>
                <p className="text-lg leading-9 text-white text-center mt-5">
                  Full website design and build for a concept team collaboration
                  platform. This website also includes a beautiful blog. I have
                  built the website and the blog in Webflow which has one of the
                  best CMS for blog hosting.
                </p>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div>
                <h1 className="text-5xl mt-16 text-center text-teal-400">
                  Chat App Website
                </h1>
                <p className="text-lg leading-9 text-white text-center mt-5">
                  This is a homepage design and build for a concept project – a
                  chat application. I designed the page first then built a
                  responsive web page using Webflow.
                </p>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://sandeeps-stunning-site-246c28.webflow.io/"
                class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
              >
                <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                <span class="relative">
                  <Image
                    className="rounded-lg object-cover"
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    src={web6}
                  />
                </span>
              </a>
              <div className="lg:flex justify-between">
                <a
                  href="#_"
                  class="px-5 py-2.5 relative rounded group text-white font-medium cursor-auto inline-block"
                >
                  <span class="absolute top-0 left-0 w-full h-full opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                  <span class="relative">Figma | Webflow</span>
                </a>
                <div className="lg:flex justify-between gap-2">
                  <a
                    href="#_"
                    class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                    <span class="relative">Live ⇑</span>
                  </a>
                  <a
                    href="#_"
                    class="px-5 py-2.5 relative rounded group cursor-auto text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-40 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>

                    <span class="relative">Read-Only Links ⇒</span>
                  </a>
                  <a
                    href="https://www.figma.com/file/PLwJPHHCd2FTOLl1rOjNyf/Chat_App?node-id=0%3A3&t=qoT2jkCekNNJiKw5-1"
                    class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                    <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                    <span class="relative">
                      <FiFigma className="w-5 h-5" />
                    </span>
                  </a>

                  <a
                    href="https://preview.webflow.com/preview/sandeeps-stunning-site-246c28?utm_medium=preview_link&utm_source=designer&utm_content=sandeeps-stunning-site-246c28&preview=6ecdfb07e8abcaef06bf201eddb42567&workflow=preview"
                    class="px-5 py-2.5 relative rounded group text-white font-medium inline-block"
                  >
                    <span class="absolute top-0 left-0 w-full h-full rounded opacity-50 filter blur-sm bg-gradient-to-br from-purple-600 to-blue-500"></span>
                    <span class="h-full w-full inset-0 absolute mt-0.5 ml-0.5 bg-gradient-to-br filter group-active:opacity-0 rounded opacity-50 from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition-all duration-200 ease-out rounded shadow-xl bg-gradient-to-br filter group-active:opacity-0 group-hover:blur-sm from-purple-600 to-blue-500"></span>
                    <span class="absolute inset-0 w-full h-full transition duration-200 ease-out rounded bg-gradient-to-br to-purple-600 from-blue-500"></span>
                    <span class="relative">
                      <SiWebflow className="w-5 h-5" />
                    </span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
        <div className="lg:flex gap-10">
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            {/* <Image src={logonew} width={100} height={100} className="mx-auto" /> */}
            <div className="w-40 h-10 mx-auto mt-0 mb-3">
              <Image
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={logonew}
              />
            </div>
            <h1 className="text-5xl font-medium text-teal-500 pt-7  ">
              Want to Work?
            </h1>
            <h3 className="text-2xl font-medium pt-8 pb-2 ">
              If you need a modern and powerful website for your business,
              startup or yourself, I am available for work. You can email me
              directly at{" "}
              <a href="mailto:ss2359215@gmail.com" className="text-teal-600">
                ss2359215@gmail.com
              </a>
            </h3>
          </div>
        </div>
      </main>
    </div>
  );
}
